import Head from 'next/head'
import Game from '../components/game'
import styles from "../styles/Home.module.css"
import CreateCharacter from './CreateCharacter'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>{"Sam's RPG Demo"}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    <CreateCharacter />
    </div>
  )
}
